name: Build & Push

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: |
          npm ci 
          git add -A
          git commit -m "Building Node Modules"
          git push 
          git checkout gh-pages
          git merge main 
          git commit -m "Deploy build to prod"
          git push 
