name: Build & Push

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci 
      - name: Deploy build to main 
        run: |
          git config --global user.name 'Dev-Laurin'
          git config --global user.email 'Dev-Laurin@users.noreply.github.com'
          git add -A
          git commit -m "Building Node Modules"
          git push 
          git checkout gh-pages
          git checkout main
          git merge -s ours gh-pages
          git commit -m "Merge gh-pages"
          git push
      - name: Deploy github pages
        run: |
          git checkout gh-pages
          git merge main 
          git commit -m "Deploy build to prod"
          git push 
