name: Build Jekyll site

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci 
      - name: Deploy build to main 
        run: |
          git config --global user.name 'Dev-Laurin'
          git config --global user.email 'Dev-Laurin@users.noreply.github.com'
          git commit -m "Building Node Modules"
          git push 
